// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzSxRlPWOBMLJ6A-aw7wpOnnpG4XMOuBQ',
    appId: '1:388069578587:web:2e188b5c3de0b88e8f6c7e',
    messagingSenderId: '388069578587',
    projectId: 'medical-a9da7',
    authDomain: 'medical-a9da7.firebaseapp.com',
    storageBucket: 'medical-a9da7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZZr6aXEWOZv9WDEoTJ7tpP6oC4zERSQ',
    appId: '1:388069578587:android:cbe86c2bb1c7ecde8f6c7e',
    messagingSenderId: '388069578587',
    projectId: 'medical-a9da7',
    storageBucket: 'medical-a9da7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6GZg6bxlycqQAM2vn7BWOKEg6e_I-9Cw',
    appId: '1:388069578587:ios:674e7cfdf1d8d45b8f6c7e',
    messagingSenderId: '388069578587',
    projectId: 'medical-a9da7',
    storageBucket: 'medical-a9da7.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6GZg6bxlycqQAM2vn7BWOKEg6e_I-9Cw',
    appId: '1:388069578587:ios:674e7cfdf1d8d45b8f6c7e',
    messagingSenderId: '388069578587',
    projectId: 'medical-a9da7',
    storageBucket: 'medical-a9da7.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzSxRlPWOBMLJ6A-aw7wpOnnpG4XMOuBQ',
    appId: '1:388069578587:web:67c9b57d2c9903f78f6c7e',
    messagingSenderId: '388069578587',
    projectId: 'medical-a9da7',
    authDomain: 'medical-a9da7.firebaseapp.com',
    storageBucket: 'medical-a9da7.appspot.com',
  );
}
